function radarPlot(group1,group2,labels,axes_limits)
% this function is to plot radarchar
% INPUTs:
%       data: data for plot
%       labels: corresponding to each colume of data

% ==============================
% plot radarchar
% ==============================
data = [group1;group2];
spider_plot(data,...
    'AxesInterval', 4,...
    'AxesPrecision', 0,...
    'AxesLabels', labels, ...
    'AxesLimits', axes_limits,...
    'AxesLabelsOffset', 0.08,...
    'AxesDisplay', 'one',...
    'AxesLabelsEdge', 'none',...
    'AxesWebType', 'circular',...
    'AxesStart', 0,...
    'Direction', 'counterclockwise',...
    'Color', [0 0.447 0.741; 0.85 0.325 0.098],...
    'FillOption', {'on', 'on','on'},...
    'FillTransparency', [0.2, 0.2]);

title('Radar Chart', 'FontSize', 13, 'FontWeight', 'bold');

% Legend properties
legend('group1', 'group2', 'group3','Location', 'southoutside');
